//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_9D8B6E_PAGINASEntities : DbContext
    {
        public DB_9D8B6E_PAGINASEntities()
            : base("name=DB_9D8B6E_PAGINASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgileInventorCategory> AgileInventorCategory { get; set; }
        public virtual DbSet<AgileInventorPost> AgileInventorPost { get; set; }
    }
}
